### ISSUE TITLE
Readme: Mention Adafruit_BusIO repository is a required dependency

### ISSUE THREAD

**Issue by gudnimg** [adafruit/Adafruit_INA260#15]
When using [PlatformIO](https://github.com/platformio) it is not enough to only include this library repo in the library dependencies. The library [Adafruit_BusIO](https://github.com/adafruit/Adafruit_BusIO) is also **required** and I think the README in this repository should mention it at the very least.

`platformio.ini` Example:

```ini
; Libraries
lib_deps =
     https://github.com/adafruit/Adafruit_BusIO
     https://github.com/adafruit/Adafruit_INA260
```

**Comment by ladyada** [comment]
ok please submit a PR for a readme update 

Arduino / Platform should be installing the **required** dependancies as documented here :)
https://github.com/adafruit/Adafruit_INA260/blob/master/library.properties#L10

**Comment by ladyada** [comment]
closing for no response
