### ISSUE TITLE
Awesome circuit! Documentation of Alert settings

### ISSUE THREAD

**Issue by drmartin1234** [adafruit/Adafruit_INA260#9]
I have read the documentation and comments and cannot find detail of how the set the Alert trip point.  Can someone please send me in the right direction?  Will need to set current trip.

**Comment by m0ivq** [comment]
In my code, I've declared my INA260 as Ina260_5V, to setup the alert function I have:

Ina260_5V.setMode(INA260_MODE_CONTINUOUS);  // continuously update the current
Ina260_5V.setAlertType(INA260_ALERT_OVERCURRENT);  // set alert mode to overcurrent
Ina260_5V.setAlertLimit(700); // set alert current threshold to 700mA
Ina260_5V.setAlertPolarity(INA260_ALERT_POLARITY_NORMAL);  // set alert polarity to active high
Ina260_5V.setAlertLatch(INA260_ALERT_LATCH_ENABLED);  // latch the alert pin until mask/enable register is read

**Comment by siddacious** [comment]
@drmartin1234 this should be addressed when PR #8 is merged!

**Comment by MichiTheSailor** [comment]
Ciao,
is there any plan when the Alert functionality will be merged to the master?
Thanks
Michi

**Comment by ladyada** [comment]
@MichiTheSailor can ya try that PR and let us know if it works? the PR needs some cleanup but we haven't been able to test it either :D

**Comment by MichiTheSailor** [comment]
Did yesterday a first code review - Looks for really good work :)
I have hardware available and will proceed within  the next days.

**Comment by ladyada** [comment]
done in https://github.com/adafruit/Adafruit_INA260/pull/14
